{
 "title": "Media Campaign Overview",
 "tags": [
  "media",
  "mlops",
  "campaign"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "API predictions_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "predictions_total" }
   ]
  },
  {
   "title": "Consumer predictions_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "consumer_predictions_total" }
   ]
  },
  {
   "title": "Consumer Last Prediction ROAS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "consumer_last_prediction" }
   ]
  },
  {
   "title": "Predicted ROAS Distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "targets": [
    { "expr": "consumer_predicted_roas" }
   ]
  },
  {
   "title": "Active Model",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "targets": [
    { "expr": "active_model" }
   ]
  }
 ]
}